### PR TITLE
hpt-360 & hpt-732 - Pages controller test backfill.

### PR DESCRIPTION
**Pull request by andjsmit**

### CODE REVIEW

**Comment by aploshay** [comment]
Suggested revisions:

pages_controller.rb:63 -- use pageds_url or pageds_path instead of raw string of "/pageds"

pages_controller_spec.rb:62 -- remove FIXME comment, replace with 2 test contexts for paged_id values

pages_controller_spec.rb:101 -- remove FIXME comment (issue resolved)

pages_controller_spec.rb:136-179 -- remove or uncomment comment block

**Comment by andjsmit** [comment]
FIXME's have been removed and "/pageds" replaced with pageds_path. Test still successful in my local. Not sure why they failed previously with pageds_path.

**Comment by aploshay** [comment]
Andy, I pushed another commit and sent you a pull request on your personal repo -- please approve it to update this pull request.

**Comment by andjsmit** [comment]
Adam: Your pull request has been merged. Thanks.

**Pull request merged**
