### PR TITLE
HPT-250: Made the browse link on the side navigation menu into a button.

### PR DESCRIPTION
**Pull request by rwingiupui**
HPT-250: This task makes the browse link on the side navigation menu into a button.

### CODE REVIEW

**Comment by andjsmit** [comment]
For the test to pass, I think all that needs done is to change line 116 in spec/controllers /catalog_controller_spec.rb from click_link to click_button

**Comment by aploshay** [comment]
This is weird; the test passes for me as written:
click_link 'sidebar_nav_browse'
with the id value, or with the link text value:
click_link 'Browse'

I'm going to try pulling the branch directly from rwing's repo and running the spec there...

**Comment by aploshay** [comment]
Okay, that same test is failing when it run it on the hpt-250 branch, so the problem does lie there somewhere.

**Comment by aploshay** [comment]
+1

**Comment by randalldfloyd** [comment]
This was merged and deployed so it can be demo'd on the server.

**Pull request merged**
