### PR TITLE
[HPT-153] Pages belonging to a paged object should form a single connected sequence

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://bugs.dlib.indiana.edu/browse/HPT-153

Tests seem to be working.  I'd appreciate comments on whether the tests are good and thorough.

app/script/purge-all.rb is a bonus:  a tool to empty a Fedora instance of non-system objects.  My test development created plenty of trash and I needed an automated cleanup.  Share and enjoy!

### CODE REVIEW

**Comment by andjsmit** [comment]
Testing: [Starting with a new paged object] - 

Worked: Creating first page, adding additional (last) pages using only previous page, adding middle page by supplying valid prev and next pages, adding new first page by only setting next page.

Failed: Editing first page(even without any changes) gives 'Prev page invalid', editing middle or last page gives 'Next page invalid'.

Does editing need to be working for this pull request to be merged or should it be added as a additional story/task?

**Comment by andjsmit** [comment]
purge-all script works great. Used it several times.

**Comment by mwoodiupui** [comment]
I think it should work whether creating or editing.  The model should take care of the linkage, period.  Don't pull until I make it so.

**Comment by mwoodiupui** [comment]
A couple of commits later, I think this should work now.  I had not considered that the links will be different when updating a page that already exists.

**Comment by andjsmit** [comment]
+1 - Worked in my dev. env.

**Pull request merged**
