### PR TITLE
[HPT 445] Field labels in Paged view controlled from locale file per paged type.

### PR DESCRIPTION
**Pull request by andjsmit**
The locale file also controls which fields get displayed as omitting a field in the locale file (currently config/locales/pagedmedia.en.yml ) will cause it not to display. If type does not exist in locale file, the default fields will be used.  Code based on Randall's Gist example: https://gist.github.com/randalldfloyd/a0820a87d35d2acda5c5 .

### CODE REVIEW

**Comment by andjsmit** [comment]
Question before merge: This branch temporarily had a copy of the newspaper package in it. One commit added it, the next took it out. Will this merge bring in the newspaper package even though it is not listed as any of the files changes? If so, I can recreate this work on a fresh branch without the newspaper package if needed.

**Comment by randalldfloyd** [comment]
I'm not sure I know the answer to that. The requested merge would seem to indicate that only the final resulting files would be merged in, but the commit itself will go into the history so I don't know if that means that the file changes associated with that commit will be available or not. Does anybody else know? If this is merged, would one expect to be able to revert back to commit 8ca4da9 or is that purely historical in the log?

**Comment by mwoodiupui** [comment]
I don't know.  Best to recreate it.  Even viewing the commit is  s l o w.

**Comment by andjsmit** [comment]
OK. Please don't merge. I'll submit another request.

**Comment by randalldfloyd** [comment]
FYI...The answer to this is yes, the commit history contains the large files for the newspapers even though they were removed before the final pull request. When I fetched all references to pick up pull requests, I got this one (#81) even though it was closed without being merged, and my local repo ballooned to 1.5 GB. This wouldn't affect people cloning develop or other branches, but it will affect anyone pulling references to pull requests. I don't know how to purge the public repo of that commit but we might want to figure it out to be friendly and good stewards of public Github.

**Comment by mwoodiupui** [comment]
I think this may be a case for "rewriting history".  If you reset HEAD back before the large files were added, and force-push, I think the subsequent commits will be orphaned and eventually garbage-collected.  It's on an abandoned, deleted branch and we all know what the problem is.  But it wouldn't hurt to try asking GitHub what they would like us to do.

**Comment by randalldfloyd** [comment]
I wonder what the effect would be of just deleting Andy's source branch. As I understand it, those commits aren't really in our repo yet, just pointers to them from the PR. From researching around it appears that there's no way to delete a PR (open or closed) but if the branch it compares against goes away, then maybe the PR would just contain orphaned pointers. So I would correct my earlier comment to say that our repo isn't the one carrying the large files because the commits weren't ever merged in. So the only problem here is for git clients who are fetching pulls from this repo (like me). I can keep ridding my local repo of it, but I'll just keep getting them every time I fetch.

**Comment by andjsmit** [comment]
The source branch has already been deleted from github. I can try deleting my fork entirely and re-forking.

**Pull request closed without merging**
