### PR TITLE
[HPT-82] Move PagedObject metadata from DC stream to new descMetadata stream

### PR DESCRIPTION
**Pull request by mwoodiupui**

### CODE REVIEW

**Comment by randalldfloyd** [comment]
Anybody else on the team want to jump in on a PR and discuss/merge? We don't want anyone under the impression that only certain ones of us are specially empowered to merge. Merging to a release branch or master might be done by a chosen gatekeeper, but PRs to develop can be reviewed/merged by anyone upon consensus.

**Comment by andjsmit** [comment]
Does this effect the web form that generates paged objects from the last sprint. Will that work need to be updated after this pull request is merged?

**Comment by mwoodiupui** [comment]
I would not think so.  Paged should encapsulate these concerns.  Other
code just refers to Paged.title and so on.  Paged is the code which
knows what that means.

**Comment by randalldfloyd** [comment]
This should just affect the final name of the datastream object, so the other Rails pieces still just know the attribute names, which haven't changed. When we get to where we should be, a test involving the form itself could ensure that the model change didn't impact it. We kind of got thrown into functionality here before we had a chance to set in the development environment completely. Meaning our tests are kind of falling by the wayside vs. driving development.

**Comment by randalldfloyd** [comment]
I'm going to merge this soon if that's okay with everyone, or if someone else would like the opportunity. We need this merged before adding the Hydra access controls hook to the model.

**Comment by andjsmit** [comment]
+1 - Merging sounds good to me.

**Pull request merged**
