### PR TITLE
[HPT-124] When page editing is called from paged view, return to paged v...

### PR DESCRIPTION
**Pull request by mwoodiupui**
...iew upon submission.

This introduces a session key "came_from" whose value names the object type (:paged, :page) which requested the edit.

### CODE REVIEW

**Comment by andjsmit** [comment]
This is not working like I had expected. When starting at a paged view, clicking on a page edit link, then updating, I am returning to the pageds listing rather than the paged view. Is this by design?

**Comment by mwoodiupui** [comment]
"return to paged view" is ambiguous.  Please specify more precisely.  I guess you want to return to the paged which owns the page?

**Comment by andjsmit** [comment]
By paged view, I mean the paged object view that owns the page object being edited and that the edit call was made from. By pageds listing, I mean the web page that list all paged objects.

So if I'm at pageds/changeme:3 and click on an page edit link which goes to pages/changeme:24/edit, upon clicking Update Page, I would expect to end up back at pageds/changeme:3

**Comment by randalldfloyd** [comment]
Should I merge this in for integration deployment or is there still discussion about the expected behavior?

**Comment by randalldfloyd** [comment]
BTW, the build on this PR failed because my original configuration for Jetty startup on Travis wasn't allowing enough time for Fedora/SOLR to be available. A new PR request has been merged that fixes that.

**Comment by mwoodiupui** [comment]
At this point I think we should leave the PR open for rework.  No point demo.ing something that we intend to change.  We may want to move the task to a more general story so that we can (a) be thorough, and (b) close the current story.

**Comment by andjsmit** [comment]
This works great now and is cleaner looking code than I thought it would be. I'm going to merge it.

**Pull request merged**
