### PR TITLE
Ran rails scaffold for Page forms [HPT-85]. Spec test not tracked.

### PR DESCRIPTION
**Pull request by andjsmit**
Trying a new pull request with out tracking the spec files created when scaffold was used to generate page image object web forms.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
The Travis failure seems unrelated to this PR.  But see my inline note.

**Comment by randalldfloyd** [comment]
Mark is correct, the CI failures showing now are from the previous PR for the page object model that we merged at the last moment of the last sprint. Until we get a story to fully plumb Travis up for rich testing, the CI result can't be the criteria for whether or not something is merged.

**Comment by andjsmit** [comment]
So is it the scaffold generated form that is causing this "leaking into the database" or is it the Page model that leads to it? When creating the form, I was looking for attributes that the user could set at this early point in development. To do this I ran - 

```
rails generate scaffold Page logical_number:string physical_number:string
```

Are there no attributes that can be used at this point by the form for simple object creation or is this a more complicated case than the Paged object creation where the form needs to create a metadata stream on the fly (something I'm not yet sure how to do)?

**Comment by andjsmit** [comment]
Yes, I had come to realize the failures were do to the Page Object model pull. But at least it is back to two failures instead of the 15 that existed before I stopped tracking the test specs my original pull created. :-)

**Comment by andjsmit** [comment]
Removing pull request (again) to be replaced with version that does not alter DB schema.

**Pull request closed without merging**
