### PR TITLE
[HPT-264] Write module that let something function as a level in a hierarchy

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://bugs.dlib.indiana.edu/browse/HPT-264

This wound up touching a lot of code, often fairly lightly.  One change to note well is that Page and Paged methods that formerly accepted/returned models (parent=/parent, for example) now accept/return PIDs.

Another change of note:  a few names have changed.  Page.paged becomes Node.parent, Paged.pages becomes Node.children, Page.prev_page and Page.next_page become Node.prev_sib resp. next_sib.

Under the hood:  Page and Paged are now derived from a superclass Node, which handles both sibling and descent relationships.  More models can be derived from Node easily and decorated with any fields and behaviors that they require.  So, for example, we can invent Section between Paged and Page, or Volume above Paged (for a periodical, perhaps) and have its hierarchial characteristics already catered for.

### CODE REVIEW

**Comment by randalldfloyd** [comment]
After noticing the Travis failure for this PR I tried running spec tests locally on a clean Jetty repo and it also fails for me on the same test.

**Comment by mwoodiupui** [comment]
Yes, I see it locally too.  It was passing earlier, so I must've
broken B while fixing A.  It's GETing
pageds/N/pages?index=1&id=SOMETHING, and coming back with
'?id=&index=1&ds_url=' which makes me think that pages are not being
indexed properly.  I could use some help on this one.

**Comment by randalldfloyd** [comment]
After a couple of days doing various tests and "what-if" refactoring, Adam and I are pretty sure we know what is causing that particular test failure, and have identified other things that are affected if there was test coverage to detect them. It appears as though making objects a sub-class of Node and not directly sub-classed to ActiveFedora somehow affects Solrization for objects that are touched anytime and saved after their initial creation. For example, new pages created and added to a paged object require updating their neighboring siblings, with the result being that all metadata and fields are present in Fedora but disappear in the Solr document of the affected page. It's like the Solrization step does not run the metadata model methods or the to_solr method on those objects. The objects do have a document in Solr and it includes all regular Fedora stuff, just not the metadata or fields from the model or ones we are deriving in the custom to_solr method.

You can see this at work in the failing test in question. What happens is that as each page is added from the factory, its previous neighbor's object is updated, so its Solr document is incomplete and doesn't contain the field the test requires. The reason it gets 1 when expecting 6 is that the final page object is not harmed because it has no next page and therefore isn't touched again. The result set you get back is one page object when it needed 1 paged object and 5 page objects. The paged object is also affected because it was touched sometime during creation of pages (presumably to update children_tesim?)

Adam has a branch that has some slight refactoring to the Page model to sub-class ActiveFedora and include Node as a module: https://github.com/aploshay/PagedMedia/tree/HPT-264_experimental_module_refactoring .  This was done not as a fix but more of a what-if change to prove the theory. In that branch it almost fixes the failing test (now you get 5 when expecting 6 because the Paged object is still sub-class of Node). We don't know what impact this change has so we aren't necessarily promoting it as a fix to the model, just a proof that Solrization is affected in the way we suspect.

**Comment by aploshay** [comment]
Looks like using Node as a mix-in works for Pages and Pageds.  I have questions about how this would scale to include hierarchical objects in between Pages and Pageds (say, "Sections"), or above Pageds (say, "Collections") -- but also don't know if we want to try to answer those questions now, or merge and then investigate them.

ActiveFedora seems to cast model search results as whatever you're searching for -- I can have a Page object with pid "changeme:206", and get a result with _either_ Page.find("changeme:206") or Paged.find("changeme:207").  The Paged search result will just have blank values for the attributes specific to Pageds.  In the Node mix-in, this is overall a helpful thing -- it lets us search for children/parents in a class-agnostic way -- but leaves me with the questions:
- Is there an elegant way to determine the "true" class of the object of a search result?  (We could potentially infer it via checking for validity, or the value presence in some required field.)
- Is there an elegant way to constrain search results to only search within the "true" class?

These questions pertain to my larger concern of what will happen when we add intermediate and additional hierarchy levels.  If we're working with a Paged, and searching children/grandchildren/etc., through unknown numbers of layers of Sections, how will we know when we've found Pages?  Or coming from a page and searching parentage, how will we know when we've landed on a Page?  It looks like what we currently have would let us build an entire ancestry tree, but I'm worried about building just a desired, constrained subtree.

(These are all early-morning, pre-coffee thoughts, so I hope I'm thinking about this right...)

IN-LINE REAL-TIME UPDATE: It looks like we can call ActiveFedora::Base.find(pid, cast: true) to return an object as its true class.  So, that answers my first question!

I also noted that the pageds_controller spec tests takes about twice as long to run now.  That may be fine, but I do want to look into that further to see if there are changes we could make to speed it up, as we did in an earlier pass.

**Comment by randalldfloyd** [comment]
So what would be the impact of going ahead and merging this now even though we haven't fully tested out collections and sections? If it passes tests and doesn't currently break paged/page functionality then we can at least avoid having a huge rebase again. Even now it says it can't be automatically merged for some reason. If we merge more pull requests it will be even harder to merge. If we get further into it and see that it still isn't yet workable, we can always revert and the worse that happens is we have to have people do pull requests again against an earlier commit level.

**Comment by aploshay** [comment]
Okay, I'm sold; I'll take a look at why it's not automatically merging, and maybe make a pull request into HPT-264 to resolve that issue.

**Comment by rwingiupui** [comment]
Sounds good to me.

Rich

**Pull request merged**
