### PR TITLE
[HPT-123] Adds link to paged view from page view if binding exists.

### PR DESCRIPTION
**Pull request by andjsmit**

### CODE REVIEW

**Comment by andjsmit** [comment]
[HPT-127] Fix added after pull request made to replace deprecated link_to_function. This method no longer exists in Rails 4.1.x which the updated gem file requires.

**Comment by andjsmit** [comment]
Another quick fix added. Turns out rails is using something called turbolinks. This speeds up page downloads by only updating the body section after an HTML request is made by an internal link. By doing so, linking to a paged view from a page view did not include the paged.js file required by the "Add Page" feature. For now, I've added data-no-turbolink to the page view links. Might be better in the future to move js code to a file that gets loaded by all pages?

**Comment by andjsmit** [comment]
FIXED: Add page feature no longer disabled after turbolink page load. JavaScript moved to rails default pageds.js.coffee file instead of an additional file.

**Comment by randalldfloyd** [comment]
+1, I think we should get this merged even though I haven't had time to bring it down and try to make it work locally. It looks well-informed and done to me.

**Pull request merged**
