### PR TITLE
[hpt-421] Updates index of all ancestors when restructuring page order.

### PR DESCRIPTION
**Pull request by andjsmit**

### CODE REVIEW

**Comment by randalldfloyd** [comment]
@andjsmit  I'm trying to figure out what this actually should do. What can I look at locally when I test the PR?

**Comment by randalldfloyd** [comment]
I believe this has the desired effect, which is to update the children to reflect potential structural changes on certain reorder actions.  

Example: if I have a paged object with Section A and Section B and I move page A1 to be after B1 in Section B, then it isn't enough to make sure the order is right. The page_struct attribute has to be rebuilt and reindexed to show the relocation.

**Comment by randalldfloyd** [comment]
Hmmm, what I just described still works even without this PR, so I'm still not sure yet what it does...

**Comment by randalldfloyd** [comment]
Anyone else care to dive into this to see what the use case is and whether or not it is needed? If we merge it and it is redundant then we are adding unnecessary time to certain actions.

**Comment by andjsmit** [comment]
I agree that it should NOT be merged if a case can't be found for when extra index updates are needed. It does add a considerable amount of time to a re-ordering. One case I haven't explored yet is going an extra layer deep than what the default score gives. A section in a section scenario. I'll try that out.

**Comment by randalldfloyd** [comment]
I was only working on it now because it was kind of leftover business from the last sprint (and to get it in before I am out for a while) but there's no rush. It's a few lines of code that should merge cleanly should people go crazy with other pull requests.

**Comment by andjsmit** [comment]
Here is a scenario that I thought this code might be needed, but in fact doesn't fix. Both this PR and the develop branch fail when the following actions are taken:

Starting from a clean copy of the ingested score, move section C into section B and "Save Reordered Pages". The resulting page still has the correct order as does the "A packaged Score" page. However, going back to the home page and looking at the left sidebar Contents, the section move is not reflected. 

However, if you move a page into the moved section as well (ie B2 -> Section C) and Re-Order, the changes will be reflected in the Contents.

This occurs in both the PR and develop branches for me.

**Comment by andjsmit** [comment]
This pull request is no longer wanted.

**Pull request closed without merging**
