### PR TITLE
[HPT-11] Ran scaffold to generate page forms.

### PR DESCRIPTION
**Pull request by andjsmit**
Ran 

```
rails generate scaffold Page logical_number:string physical_number:string 
```

to create form for page image object. 
Has only two fields: logical_number and physical_number.

### CODE REVIEW

**Comment by andjsmit** [comment]
I'm going to either revise or remove the pull request once I understanding what to do about the Travis CI failure. So please don't Merge yet.

**Comment by randalldfloyd** [comment]
Andy, you may have figured this out by now, but the reason the test suite is failing is because Travis does not have the full Fedora/SOLR environment it needs to create and index objects. I will be writing a story for the backlog saying we need to get that working, so for now you can just stop tracking/committing test files that got put down into the spec directory (generated automatically during scaffolding for 'pages')

**Comment by mwoodiupui** [comment]
Or comment out the integration-type tests.
That story about integration/functional testing might explore the idea I came across somewhere:  push those tests down to e.g. spec/integration and write a rule that only runs them when we want them run.  Sorry, I don't have the details worked out.

**Comment by randalldfloyd** [comment]
Yeah Andy, the whole topic of testing and getting Travis working for us is worthy of a sprint story and is too big to keep you roadblocked right now, so your choice as to whether you want to move the spec tests out of the way or comment them out (probably a lot of commenting!) On my pull request I think I either didn't have the generator lay out spec tests or I moved them out of the way of tracking before committing.
On Adam's recent pull request, it was at the end of the sprint and we just merged even though it had the same problem. I'm fine with that if no objections from anyone else.

**Comment by andjsmit** [comment]
Thanks Mark and Mark for your hints and suggestions. I've reverted my branch and made a new commit not tracking the spec files. I'll close this request and open a new one.

**Pull request closed without merging**
