### PR TITLE
HPT-416

### PR DESCRIPTION
**Pull request by randalldfloyd**
Improves performance and efficiency of various create/update actions by creating callback methods for validating siblings and for updating sibling linkage, with flags to bypass when appropriate.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
I'm uneasy about the proliferation of flags to ignore model consistency checks, but in this case I think I understand the need.  +1

**Comment by andjsmit** [comment]
The batch ingest (pmp:process_batches) is not working for me on this pull request.

Error: Processing 10 pages:Processing Sections: ABORTING: problem saving Section
{:base=>["must have one or both siblings if parent has children"]}

**Comment by aploshay** [comment]
Andy, batch ingest being broken on HPT-416 is a known issue -- it's subtask HPT-419 inside HPT-416.

**Comment by randalldfloyd** [comment]
This PR doesn't completely finish HPT-416 but I want to get it into develop ASAP because the introduction of callbacks and flags to bypass expensive checks is important and we don't want develop to drift too far given the nature of the commits to core stuff like Node.

**Comment by andjsmit** [comment]
OK. Checkout develop to ingest test score, then went back to PR. Moving pages between sections works as expected, which is the battle I've been trying to fight. 

+1 for me!

**Comment by randalldfloyd** [comment]
@mwoodiupui I know what you mean about ignoring consistency checking, but right now it's kind of like having a chronic illness that until/unless you can find the root cause of, it's at least good to have a coping mechanism for. In this case just having the option to skip checks to improve performance in either testing or batch ingest is good to have even if we eventually don't really need them.

**Pull request merged**
