### PR TITLE
[HPT-529] Update common page elements

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://bugs.dlib.indiana.edu/browse/HPT-529

### CODE REVIEW

**Comment by mwoodiupui** [comment]
Failing tests due to problems with the attempt to simplify the search controls.

**Comment by mwoodiupui** [comment]
Tests pass now, after restoring search-by droplist.

**Comment by andjsmit** [comment]
Reviewing: I notice that the left column Browse by navigation disappears when you go to a paged view. I know we have run into this before (not having the blacklight navigation available on a paged view.) But now without the paged browse, no left column navigation will be available. 

Is there anyway to include the browse navigation on the paged view? Without it, none of the other wireframes will be correct.

**Comment by mwoodiupui** [comment]
Yes, I just saw this as well.  I poked around a bit but found no good way to do this.  The bits of Blacklight that create those features all seem to assume that they're called from the catalog view, and if you try to use that sidebar partial from any other view it can't find things that it needs.  I think we'd have to copy'n'hack a number of BL files to make this work.

I am surprised to find through Google that nobody is asking about such things.  Are we thinking about this wrong-way-round?

How do we suppose people would use the browse sidebar, when they're down in the detail pages?  What do we actually need on those pages to support what people really do with them?

**Pull request merged**
